{
    "status": "FAILURE",
    "httpStatusCode": 400,
    "httpStatus": "BAD_REQUEST",
    "error": {
        "errorStackTrace": "AccountNumber:  | RadioId:  | x-forwarded-for: [10.128.36.161] | URL: /services/account/credential-recovery/password/send-email | Exception: AccountServiceException#null | StackTrace: CredentialManagementServiceImpl.java:93 | ErrorType: null | ErrorMessage: ERROR : [errorCode : USER_NOT_FOUND_IN_IDM, errorPropKey : error.account.service.user.not.found.in.idm, errorType : CHECKED, errorLevel : FIELD, statusCode : 400 BAD_REQUEST, errorMessage : null | , sourceErrorCode : null] | FullStackTrace: ",
        "logId": "2bc55a72-4b27-4ea7-898c-72e0d57105e8",
        "fieldErrors": [{ "errorCode": "USER_NOT_FOUND_IN_IDM", "errorPropKey": "error.account.service.user.not.found.in", "errorType": "BUSINESS", "fieldName": "idm" }]
    }
}
